### ISSUE TITLE
SRT support

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/elv-live-stream#107]
Add SRT / Transport Stream distribution support.

### Create

RTP protocol to URL type 

### General Config

Add source URL - allow change (only if inactive/uninitialized)

### Recording Config

“Record Transport Stream Source”    https://github.com/eluv-io/elv-live-stream/issues/97
    (live_recording.recording_config.recording_params.copy_mpegts  true|false)

SRT Password         (live_recording.recording_config.recording_params.srt_passphrase)

### Transport Stream Distribution (new tab)

<img width="737" alt="Image" src="https://github.com/user-attachments/assets/301eca6a-e59c-4193-bc41-7e52a1ca6af2" />

Grayed out if not “Record Transport Stream Source”

Quick links:
  srt-us-west –   
  srt-us-north - 

Generate SRT URL

Region  |    Label   |  Secure Signature    [Generate]       →  live stream site object

Make an Editor Signed Token:

```
{
  iat:
  exp:
  ctx:
    usr: {
       label:    (may also add ‘email’ in the future)
    }
}
```

**Comment by elv-gerald** [comment]
On the stream detail view page, if I stop a running stream it appears that the app crashes
Here are the interesting errors from the console truncated.
```
TypeError: Cannot read properties of undefined (reading 'includes')
    at index-CqA45zWs.js:258:144484
    at Qv (index-CqA45zWs.js:40:24283)
    at Af (index-CqA45zWs.js:40:42409)
    at aE (index-CqA45zWs.js:40:36625)
...

Uncaught TypeError: Cannot read properties of undefined (reading 'includes')
    at index-CqA45zWs.js:258:144484
    at Qv (index-CqA45zWs.js:40:24283)
    at Af (index-CqA45zWs.js:40:42409)
    at aE (index-CqA45zWs.js:40:36625)
...

TypeError: Cannot read properties of undefined (reading 'searchParams')
    at JEe.<anonymous> (index-CqA45zWs.js:258:184097)
    at Generator.next (<anonymous>)
    at KO (index-CqA45zWs.js:42:6173)
    at <unnamed flow> - runid: 88 - yield 1 (index-CqA45zWs.js:42:5992)
    at v (index-CqA45zWs.js:42:22998)
```


https://github.com/user-attachments/assets/535b71d3-d933-49e4-a227-b893e1f58050

**Comment by elv-zenia** [comment]
> On the stream detail view page, if I stop a running stream it appears that the app crashes Here are the interesting errors from the console truncated.
> 
Fixed on demo.

**Comment by elv-gerald** [comment]
Enabling/disabling Transport Stream should only be allowed when a stream is stopped, uninitialized or inactive. Right now I can toggle the check box on "running" and "starting" states, it should be greyed out during these 2 states. 

![Image](https://github.com/user-attachments/assets/541f375c-547f-46ce-a21f-58512c35063d)

**Comment by elv-gerald** [comment]
Should the Enabling/disabling Transport Stream toggle be working? I toggled it but I do not see any json key added to my config for the path `live_recording.recording_config.recording_params.copy_mpegts`

**Comment by elv-gerald** [comment]
From Serban in slack

> In the live stream manager - change the name of the stream in General Config, Save - we go back to the list without refreshing the name (I have to refresh manually to get the new name)

**Comment by elv-zenia** [comment]
> Occasionally on the listing pages I see the URL disappear on some running streams. I am not sure on the repro yet but I have seen it happen a couple times while navigating around.
> 
Fixed on demo. Looks like the url was getting loaded from the metadata at the wrong path when clicking into the stream details view.

**Comment by elv-zenia** [comment]
> Enabling/disabling Transport Stream should only be allowed when a stream is stopped, uninitialized or inactive. Right now I can toggle the check box on "running" and "starting" states, it should be greyed out during these 2 states.
> 
Fixed on demo.

**Comment by elv-zenia** [comment]
> Should the Enabling/disabling Transport Stream toggle be working? I toggled it but I do not see any json key added to my config for the path `live_recording.recording_config.recording_params.copy_mpegts`
> 
Fixed on demo. This needed support for the copy_mpegts setting in the client-js Configure api

**Comment by elv-zenia** [comment]
> From Serban in slack
> 
> > In the live stream manager - change the name of the stream in General Config, Save - we go back to the list without refreshing the name (I have to refresh manually to get the new name)

Fixed on demo

**Comment by elv-gerald** [comment]
On prod dev we noticed that the copy buttons for quick links appear to not be working. After clicking the copy button there is nothing on my clipboard to paste

![Image](https://github.com/user-attachments/assets/ab552bdd-f018-4134-93cd-d7a61bd41418)

**Comment by elv-zenia** [comment]
> On prod dev we noticed that the copy buttons for quick links appear to not be working. After clicking the copy button there is nothing on my clipboard to paste
> 
> UPDATE: I notice the copy/paste works if the stream is "editable" but once I make it public it does not work.
> 
Fixed both issues on demo and prod-dev. Also updated the Quick Links section to use a table, removed the Secure Signature option for now (since there's no backend support), fixed the broken url's on prod-dev, and restricted Transport Stream setting + tab to UDP | SRT | RTP.

**Comment by elv-gerald** [comment]
I tried deleting an SRT url on demo and I got an error. Here is what I saw

```
DataCloneError: Failed to execute 'postMessage' on 'Window': #<Object> could not be cloned.
    at F3.SendMessage (index-DYUtzmcV.js:157:14683)
    at F3.<computed> [as ReplaceMetadata] (index-DYUtzmcV.js:157:13616)
    at JEe.<anonymous> (index-DYUtzmcV.js:258:187283)
    at Generator.next (<anonymous>)
    at JO (index-DYUtzmcV.js:42:6173)
    at <unnamed flow> - runid: 83 - yield 2 (index-DYUtzmcV.js:42:5992)
    at v (index-DYUtzmcV.js:42:22998)
```

![Image](https://github.com/user-attachments/assets/b31df319-921e-45cf-b36f-0d254b41ec2f)

**Comment by elv-zenia** [comment]
> I tried deleting an SRT url on demo and I got an error. Here is what I saw
> 
> ```
> DataCloneError: Failed to execute 'postMessage' on 'Window': #<Object> could not be cloned.
>     at F3.SendMessage (index-DYUtzmcV.js:157:14683)
>     at F3.<computed> [as ReplaceMetadata] (index-DYUtzmcV.js:157:13616)
>     at JEe.<anonymous> (index-DYUtzmcV.js:258:187283)
>     at Generator.next (<anonymous>)
>     at JO (index-DYUtzmcV.js:42:6173)
>     at <unnamed flow> - runid: 83 - yield 2 (index-DYUtzmcV.js:42:5992)
>     at v (index-DYUtzmcV.js:42:22998)
> ```
> 
Fixed on demo and prod dev

**Comment by elv-gerald** [comment]
For the token time range, how do I unset this? I noticed after I picked a time I cannot unset it and I do not see anything clear on how to unset it unless I navigate away from the page.

![Image](https://github.com/user-attachments/assets/208e988c-398a-4029-8dc6-2e162f57336e)

**Comment by elv-zenia** [comment]
> For the token time range, how do I unset this? I noticed after I picked a time I cannot unset it and I do not see anything clear on how to unset it unless I navigate away from the page.
> 
Fixed this on demo and prod dev. I added a way to clear the selected value. Should we make any of these fields required?
Also, you'll notice some small design changes. I'm halfway through this part but just wanted to make a note that this is intentional, just partially done.

**Comment by elv-gerald** [comment]
It appears we might have some info missing in the tokens generated for quick links? I created a quick link with a start and end date but noticed I cannot get playout to work. 

I noticed the following when I decode the token with `elv tools decode`
```
❯ elv tools decode aessjcEcSQNZViV8bpxjDLhPy6VHm1NUxsBhoMusKYvqqKyBfmUscdw8CFoGwsdmoVnxV1ra9PyrkticWyquqRqmC1o23RwmqQF2vHwdYEqmyyAEYtzyK2muXnmB44vjCmu5YWkZiESPhD6edSpRgK72YdoDga64gT4vfynepKGFdQLJztAvMGpJZyGhDXtkXYu3aNHNTbnAPMCJKk41iqXFMDwT7PA6kNMaBjGAggggEA6SEsPTtjgKn2JuMvxqd9z6owDbSVKwCWPUEyMU97ZCoDqRjbx53wYaSqVPxsFfiq13qtjpsUXHg4MM5H2EZpMvtmtPbVFNigqg6xVUtv
==> aessjcEcSQNZViV8bpxjDLhPy6VHm1NUxsBhoMusKYvqqKyBfmUscdw8CFoGwsdmoVnxV1ra9PyrkticWyquqRqmC1o23RwmqQF2vHwdYEqmyyAEYtzyK2muXnmB44vjCmu5YWkZiESPhD6edSpRgK72YdoDga64gT4vfynepKGFdQLJztAvMGpJZyGhDXtkXYu3aNHNTbnAPMCJKk41iqXFMDwT7PA6kNMaBjGAggggEA6SEsPTtjgKn2JuMvxqd9z6owDbSVKwCWPUEyMU97ZCoDqRjbx53wYaSqVPxsFfiq13qtjpsUXHg4MM5H2EZpMvtmtPbVFNigqg6xVUtv:
    op [validate auth token] kind [invalid] type [editor-signed] sig_type [ES256K] format [json-compressed] token [{"txh":"0x0000000000000000000000000000000000000000000000000000000000000000","adr":"0x761f45287ea364db6b216bd655910430afa3e839","spc":"ispc3ANoVSzNA3P6t7abLR69ho5YPPZU","sub":"iusr2eSw8JYBroWi4EgT3gU723Ky8wHi","gra":"read","iat":"2025-05-16T21:02:12.088Z","exp":"","ctx":{"usr":{"label":"test with date"}},"cnf":{}}] cause [error-list count [3]
    	0: op [validate field] kind [invalid] reason [qid missing]
    	1: op [validate field] kind [invalid] reason [expires missing]
    	2: op [validate field] kind [invalid] reason [expires before issued at] expires [0001-01-01T00:00:00.000Z] issued_at [2025-05-16T21:02:12.088Z]
    ]
```

With the anonymous token `elv tools decode` for the same object it does not complain. This token works for playout.
```
❯ elv tools decode aessjc3A17YffeRDcEFqkV2ijvnUAN4wcNj7PjihzTagCGisvqAbo8PRB4ERUstkcZTL2LZ4Xes4YoYUt1zYc4nLr2SzD5mRuPHDysBb3dUDsCB4nDMM9bKJXEqkokZfjhLAn2ctMjfQCL7vUkxGTWkTFxSpACyF4SSbBjUGKMaDV6uwbZP5pNcPMk8peJdiN55FLM9dFZaFtxh3vQ7NsYuL84FdtkugJzkcSg3Ay2hZaULUpMDgf1Kb8xpLwEPbLSFzE5dEJs1oVbHbTb6doYzVseQJ86PDM87y4A6QRqeTrCjZsPEscDzurXcxHVxwNQKBbrEC7awfiDPSM9EXN1oLSHBxkGd1VkuhRxR8q1PWxf2cxU7vASkWrMAuDQ9x1zniRKwqAG94XC7Q
==> aessjc3A17YffeRDcEFqkV2ijvnUAN4wcNj7PjihzTagCGisvqAbo8PRB4ERUstkcZTL2LZ4Xes4YoYUt1zYc4nLr2SzD5mRuPHDysBb3dUDsCB4nDMM9bKJXEqkokZfjhLAn2ctMjfQCL7vUkxGTWkTFxSpACyF4SSbBjUGKMaDV6uwbZP5pNcPMk8peJdiN55FLM9dFZaFtxh3vQ7NsYuL84FdtkugJzkcSg3Ay2hZaULUpMDgf1Kb8xpLwEPbLSFzE5dEJs1oVbHbTb6doYzVseQJ86PDM87y4A6QRqeTrCjZsPEscDzurXcxHVxwNQKBbrEC7awfiDPSM9EXN1oLSHBxkGd1VkuhRxR8q1PWxf2cxU7vASkWrMAuDQ9x1zniRKwqAG94XC7Q:
    aessjc3A17YffeRDcEFqkV2ijvnUAN4wcNj7PjihzTagCGisvqAbo8PRB4ERUstkcZTL2LZ4Xes4YoYUt1zYc4nLr2SzD5mRuPHDysBb3dUDsCB4nDMM9bKJXEqkokZfjhLAn2ctMjfQCL7vUkxGTWkTFxSpACyF4SSbBjUGKMaDV6uwbZP5pNcPMk8peJdiN55FLM9dFZaFtxh3vQ7NsYuL84FdtkugJzkcSg3Ay2hZaULUpMDgf1Kb8xpLwEPbLSFzE5dEJs1oVbHbTb6doYzVseQJ86PDM87y4A6QRqeTrCjZsPEscDzurXcxHVxwNQKBbrEC7awfiDPSM9EXN1oLSHBxkGd1VkuhRxR8q1PWxf2cxU7vASkWrMAuDQ9x1zniRKwqAG94XC7Q
    {
      "txh": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "adr": "0x761f45287ea364db6b216bd655910430afa3e839",
      "spc": "ispc3ANoVSzNA3P6t7abLR69ho5YPPZU",
      "lib": "ilib3xjQjKgtB1d1aKwEwaB1hUioYFar",
      "qid": "iq__3xqo7NhXBT5RXjHVGFdwB81Q1H88",
      "sub": "iusr2eSw8JYBroWi4EgT3gU723Ky8wHi",
      "gra": "read",
      "iat": "2025-05-16T20:55:19.087Z",
      "exp": "2025-05-17T20:55:19.087Z",
      "cnf": {}
    }
    TOKEN                  400b  PREFIX + BODY | aessjc3A17YffeRDcEFqkV2ijvnUAN4wcNj7PjihzTagCGisvqAbo8PRB4ERUstkcZTL2LZ4Xes4YoYUt...
    PREFIX                   6b  aessjc | aes=editor-signed s=ES256K jc=json-compressed
    BODY                   394b  base58(SIGNATURE + PAYLOAD)
    SIGNATURE + PAYLOAD    289b  289b * 138 / 100 + 1 = 399b (>= 394b)
    SIGNATURE               66b  ES256K_ErRMJXYvspminYQGXBGopeo3qrrHE9fFXwiK5D3hUUAgWywXSA5vaGqtuWRemVbCKCzcEVzB86p4QZTRhQaNrLHkT
    PAYLOAD                223b  json-compressed
    json                   264b  {"adr":"dh9FKH6jZNtrIWvWVZEEMK+j6Dk=","sub":"iusr2eSw8JYBroWi4EgT3gU723Ky8wHi","spc":"ispc3ANoVSzNA3P6t7abLR69ho5YPPZU","iat":1747428919087,"exp":1747515319087,"gra":"read","ctx":{},"qid":"iq__3xqo7NhXBT5RXjHVGFdwB81Q1H88","lib":"ilib3xjQjKgtB1d1aKwEwaB1hUioYFar"}
```

**Comment by elv-gerald** [comment]
We also added persistent settings for the ttl. 

it is working but I noticed it throws off the logic for the front end on this table since this table depends on ttl. I see with your case you set persistent to true but ttl get deleted hence the table acting funky.

![Image](https://github.com/user-attachments/assets/57f7b865-f1b5-44fa-95b9-ce66c45a3127)

**Comment by elv-zenia** [comment]
> We also added persistent settings for the ttl.
> 
> it is working but I noticed it throws off the logic for the front end on this table since this table depends on ttl. I see with your case you set persistent to true but ttl get deleted hence the table acting funky.
> 
Fixed on demo and prod-dev.

**Comment by elv-gerald** [comment]
@elv-serban 
One thing to note is that right now it appears tokens cannot be made without an expiration time? This is at least what I can tell from my testing. To get around creating quick links with no expiration we have resorted to use 100 year tokens so in the table you will see these tokens with 100 year life spans. Is there a way to create tokens with start and end dates to get around this?

**Comment by elv-gerald** [comment]
After yesterdays discussion we can remove the persistent setting for ttl. We will handle that on a different deployment and focus on SRT for now. Ill make a different ticket for the persistent setting so we dont forget about it.

**Comment by elv-zenia** [comment]
> After yesterdays discussion we can remove the persistent setting for ttl. We will handle that on a different deployment and focus on SRT for now. Ill make a different ticket for the persistent setting so we dont forget about it.

Changed on demo and prod-dev. Side note: design changes are underway.

**Comment by elv-gerald** [comment]
![Image](https://github.com/user-attachments/assets/673aa5ad-1a08-44e5-8675-a68979f540c2)
Couple bugs I notice

- When creating tokens with dates I noticed the start time is shown in 24 hour format with a PM after it, no need for that if we show things in 24 hour time
- Picking an endtime is shown in in 12 hour format while the start time is 24 hour format We should stick to 1 to avoid confusion. I prefer 24 hour time for these things, @elv-serban do you have a preference?
- There is nothing stopping me from creating a token on the same date but I can set the end time before the start time. This results in a bad token, I created a link with the times above and I see this error with `elv tools decode` 
```
op [validate field] kind [invalid] reason [expires before issued at] expires [2025-05-21T22:29:35.000Z] issued_at [2025-05-21T22:29:35.676Z]
```

**Comment by elv-gerald** [comment]
After I have 1 saved linked created, if I create another one it overwrites the original one. Seems like some logic bug that keeps overwritting the original saved link?

https://github.com/user-attachments/assets/18f724a3-5ee5-4dee-b1f5-b96d3b6c8b54

**Comment by elv-gerald** [comment]
It appears that with public streams we still need a token. I cannot get playout from an SRT egress unless I have a token. This is the error ffplay mentions

```
15:49:10.446364/!W:SRT.cn: @563654045: processConnectResponse: rejecting per reception of a rejection HS response: ERROR:PEER
15:49:10.446391/!W:SRT.cn: @563654045: processAsyncConnectRequest: REJECT reported from HS processing: Peer rejected connection - not processing further
```

On prod @elv-serban created some SRT egress links for public streams but he used a legact token for these public streams, its a very short token. Maybe we can make a token like this for these public streams? Ill share of the links and token with you @elv-zenia .

**Comment by elv-zenia** [comment]
> After I have 1 saved linked created, if I create another one it overwrites the original one. Seems like some logic bug that keeps overwritting the original saved link?
> 
> This also happens with quick links (not present in video below)
> 
Oof 🤦🏼 . Fixed on demo and prod-dev

**Comment by elv-gerald** [comment]
I am able to create saved links without specifying a region nor a label. Is it possible to for the user to have these filled out when creating  a saved link?

<img width="1200" alt="Image" src="https://github.com/user-attachments/assets/5eb7e557-c3d8-442d-ba14-192ad4e0d433" />

**Comment by elv-gerald** [comment]
When I have 1 or 2 saved links created there is a gap at the bottom of the table. Its more apparent with one item on the table. Once you have 3 items on the table the gap goes away 

<img width="1205" alt="Image" src="https://github.com/user-attachments/assets/77f217d9-dea7-40c6-b543-4ae64ac0126f" />

**Comment by elv-gerald** [comment]
Not sure what is going on but I cannot create any quick links. I get an error message with no explanation and no console errors either. 

https://github.com/user-attachments/assets/85858218-ac00-40e9-adfa-622cab1b6fee

**Comment by elv-gerald** [comment]
This might be a design over sight but I once I have a saved link created I have no way of telling the exact time the token will expire. I only have the date.

<img width="278" alt="Image" src="https://github.com/user-attachments/assets/52872f02-5fb8-4682-8855-00c761bfd249" />

**Comment by elv-gerald** [comment]
I notice when I create a new saved link the form does not clear, if I try to save another without changing the region the resulting saved link has no region.

Below I create a new saved link and then another to demonstrate the issue.

https://github.com/user-attachments/assets/2c7813cc-5495-40e1-ab4d-19cb10714394

**Comment by elv-gerald** [comment]
Is it possible to throw a similar styled notification when a link gets updated? Right now when updating a link the modal just disappears. The only indicator that something has changed is the values in the table will change but that is only if you are paying close attention, its a lot harder to spot that the update was a success when you have several items in the table.

<img width="475" alt="Image" src="https://github.com/user-attachments/assets/4e6d5c30-3186-421c-9b96-30648e538fdc" />

**Comment by elv-gerald** [comment]
I notice when I update the node for a link the node drop down always says "automatic".


Below I update a link by setting a different node, the second time I go to update the link the node drop down shows "automatic". 
<img width="475" alt="Image" src="https://github.com/user-attachments/assets/58804204-2489-4699-9604-ceb4b51cf0f9" />

**Comment by elv-gerald** [comment]
For the update modal can we make the update button unclikable/greyed out until the user has changed something in the form? Right now I can open the modal and update causing an unnecessary transaction.

https://github.com/user-attachments/assets/d9db146e-48e1-41e3-a353-63b7f89ff5aa

**Comment by elv-gerald** [comment]
Not sure if this design is intentional but the gap between the form and table in Quick links is a lot smaller when compared to the gap in Saved links.

<img width="1326" alt="Image" src="https://github.com/user-attachments/assets/eff3697e-83bf-4d8e-80e2-26c869548b16" />

**Comment by elv-gerald** [comment]
@elv-serban when updating links should we show a warning that the URL will change? I feel like users might think the url (in particular the token) stays the same when only updating the dates.

**Comment by elv-gerald** [comment]
On the update link modal is there any way we can fit this row better without having to scroll left or right?

<img width="1218" alt="Image" src="https://github.com/user-attachments/assets/fd967c20-854d-4ad8-b5dd-96517b01c2d8" />

**Comment by elv-gerald** [comment]
> I also updated the date picker on the Playout Config tab.

I tested on the playout tab and I get an error when I try to save a DVR start time with the new picker. Luckily I get a console error with that

```
index-BWU6mDBc.js:209 Unable to apply settings TypeError: f.toISOString is not a function
    at Yke.<anonymous> (index-BWU6mDBc.js:258:208124)
    at Generator.next (<anonymous>)
    at kN (index-BWU6mDBc.js:42:6173)
    at <unnamed flow> - runid: 243 - yield 4 (index-BWU6mDBc.js:42:5992)
    at v (index-BWU6mDBc.js:42:22998)
```

**Comment by elv-zenia** [comment]
> I am able to **create and update saved** links without specifying a region nor a label. Is it possible to force the user to have these filled out when creating a saved link?
> 
I want to spend more time on better validation. For now, the Generate | Update buttons are disabled if there's no region or label.

**Comment by elv-zenia** [comment]
> > I also updated the date picker on the Playout Config tab.
> 
> I tested on the playout tab and I get an error when I try to save a DVR start time with the new picker. Luckily I get a console error with that
> 
Fixed on demo and prod dev.

> When I have 1 or 2 saved links created there is a gap at the bottom of the table. Its more apparent with one item on the table. Once you have 3 items on the table the gap goes away
> 
Fixed and demo and prod dev

**Comment by elv-zenia** [comment]
> Not sure what is going on but I cannot create any quick links. I get an error message with no explanation and no console errors either.
> 
Fixed on demo and prod dev.

**Comment by elv-gerald** [comment]
When I try to edit a quick link the modal title mentioned "Update SRT Saved Links" instead of "Update SRT Quick Link"
I am also not able to update the quick link. I tried picking a new node in the drop down but the Update button stays greyed out.

![Image](https://github.com/user-attachments/assets/8244392c-5d6d-47c0-ae2f-ef026d20f545)

**Comment by elv-zenia** [comment]
> For the update modal can we make the update button unclikable/greyed out until the user has changed something in the form? Right now I can open the modal and update causing an unnecessary transaction.
> 
Fixed on demo and prod dev.

> Not sure if this design is intentional but the gap between the form and table in Quick links is a lot smaller when compared to the gap in Saved links.
> 
Fixed on demo and prod dev.

**Comment by elv-gerald** [comment]
When I create a saved link I see the form resets but the region still stays the same in the form. Its like displayed but also being treated as an empty value. 
Here I crated a new saved link and you can see some of the values reset but the region stays selected on the drop down list but gets treated as its empty.

https://github.com/user-attachments/assets/70c6149d-c177-4c1a-b8cc-91b5947edc6a

**Comment by elv-gerald** [comment]
When I open links to modify, the region dropdown still shows automatic for a split second. 

https://github.com/user-attachments/assets/0d6a34c9-bcf6-49ee-bdfe-4b9b0cd324f3

**Comment by elv-zenia** [comment]
> It appears that with public streams we still need a token. I cannot get playout from an SRT egress unless I have a token. This is the error ffplay mentions
> 
> ```
> 15:49:10.446364/!W:SRT.cn: @563654045: processConnectResponse: rejecting per reception of a rejection HS response: ERROR:PEER
> 15:49:10.446391/!W:SRT.cn: @563654045: processAsyncConnectRequest: REJECT reported from HS processing: Peer rejected connection - not processing further
> ```
> 
> On prod [@elv-serban](https://github.com/elv-serban) created some SRT egress links for public streams but he used a legact token for these public streams, its a very short token. Maybe we can make a token like this for these public streams? Ill share of the links and token with you [@elv-zenia](https://github.com/elv-zenia) .

Fixed on demo and prod dev.

**Comment by elv-gerald** [comment]
![Image](https://github.com/user-attachments/assets/10574f34-09d0-489d-b11f-d14aad8a7609)

The update notification looks like it shows the programatical name for the link that was updated.

Is it possible to do the following?
- For Quick links use the displayed region name? so show "NA Southwest" instead of "na-west-south"
- For Saved links use the label name?

**Comment by elv-zenia** [comment]
> The update notification looks like it shows the programatical name for the link that was updated.
> 
> Is it possible to do the following?
> 
> * For Quick links use the displayed region name? so show "NA Southwest" instead of "na-west-south"
> * For Saved links use the label name?

Fixed on demo and prod dev.

> When I open links to modify, the region dropdown still shows automatic for a split second.
> 
Fixed on demo and prod dev. I added a loader, which might still need to be improved, but it's better than before.


> When I create a saved link I see the form resets but the region still stays the same in the form. Its like displayed but also being treated as an empty value. Here I crated a new saved link and you can see some of the values reset but the region stays selected on the drop down list but gets treated as its empty.
> 
Fixed on demo and prod dev.

**Comment by elv-gerald** [comment]
I still see the the dashed region names when updating quick links. The Saved links is working and shows the label now

<img width="501" alt="Image" src="https://github.com/user-attachments/assets/2083e5d8-8f9c-4098-94e1-16b4a642de98" />

**Comment by elv-gerald** [comment]
Based on todays feedback, can we add the region name when updating a quick link

<img width="1404" alt="Image" src="https://github.com/user-attachments/assets/8d98d06c-3b3d-4137-91ae-7d0bf49b9703" />

**Comment by elv-zenia** [comment]
> I still see the the dashed region names when updating quick links. The Saved links is working and shows the label now
> 
Ah somehow missed that one. Fixed on demo and prod dev

> Based on todays feedback, can we add the region name when updating a quick link
> 
Added this on demo and prod dev

**Comment by elv-gerald** [comment]
When updating quick links, I noticed the region name is using the name with the dashes.

![Image](https://github.com/user-attachments/assets/fe283221-8b77-49ad-b5d7-1f4ab90b6e76)

**Comment by elv-zenia** [comment]
> When updating quick links, I noticed the region name is using the name with the dashes.
> 
This is fixed on demo and prod dev.

> This behavior returned, I can update links without having modified anything causing an unnecessary commit. I have a feeling the fix for the node showing up as "automatic" for split second might have caused this.
> 
This is fixed on demo and prod dev.

**Comment by elv-zenia** [comment]
I changed the quick link logic from saving the entire link in the site object to saving the region. The url will be generated on page load. If the user edits the link and saves a new host, that new url will live for the life of the current page. So a Refresh will change the url value. This is deployed to demo and prod dev.

**Comment by elv-gerald** [comment]
I recreated my stream on demo and I get this error when I try to create a quick link. Saved links works.

```
Egress Test SRT
iq__yyH1aUiD89EvicuApnT1RB2GbNA
```

![Image](https://github.com/user-attachments/assets/46312091-be76-4487-92e6-f7145c19b306)

**Comment by elv-gerald** [comment]
I am able to create a saved link with a space as the label name.

![Image](https://github.com/user-attachments/assets/6fcc75b1-0de4-4cf4-8844-5e6911358a10)

**Comment by elv-gerald** [comment]
Can we limit the name size or at least have some character limit on what is displayed on the table? If I created something stupid long it throws off the table sizing.  

![Image](https://github.com/user-attachments/assets/a76c857a-df7e-443b-8361-5f4d619322da)

It also throws off the notification sizing

![Image](https://github.com/user-attachments/assets/4dd37ce3-b124-4450-b96d-d6225b4337b8)

**Comment by elv-zenia** [comment]
> Can we limit the name size or at least have some character limit on what is displayed on the table? If I created something stupid long it throws off the table sizing.
> 
> ![Image](https://github.com/user-attachments/assets/a76c857a-df7e-443b-8361-5f4d619322da)
> 
> It also throws off the notification sizing
> 
> ![Image](https://github.com/user-attachments/assets/4dd37ce3-b124-4450-b96d-d6225b4337b8)

I went down a design rabbit hole with this one.
So the notification message will now front-load the core message and place the item name at the end — e.g., “Link updated for Some Cool Stream.” The notification will show a maximum of two lines, so if truncation occurs, only the item name is shortened, preserving the core message. Plus, this will place more emphasis on the main action. 
Also, introduced a max width for the label column in the table.
Deployed to demo and prod dev.

**Comment by elv-zenia** [comment]
> I am able to create a saved link with a space as the label name.
> 
Deployed a fix to demo and prod dev.

**Comment by elv-gerald** [comment]
Quick link tokens do not get updated when I try this scenario.

In the stream detail view page: 
1. Start with a public stream
2. Set stream to "editable"
3. Navigate to transport Stream Tab
4. Copy a quick link
5. The token used is a legacy token that is used for public SRT egress and will not work now that the stream is "editable".

This only applies to quick links since those are always dynamic.

**Comment by elv-zenia** [comment]
> Quick link tokens do not get updated when I try this scenario.
> 
> In the stream detail view page:
> 
> 1. Start with a public stream
> 2. Set stream to "editable"
> 3. Navigate to transport Stream Tab
> 4. Copy a quick link
> 5. The token used is a legacy token that is used for public SRT egress and will not work now that the stream is "editable".
> 
> This only applies to quick links since those are always dynamic.

Oh good catch. I deployed a fix for this. When setting the permission using elv-client-js, there needs to be a buffer afterward. Not sure why but this is what the frowser does. Making a note because I want to explore this and see if I can fix it...

**Comment by elv-gerald** [comment]
Deployed to prod.
